server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    default_type application/json;

    # GET /users
    location = /users {
        try_files /users.json =404;
    }

    # GET /users/{email}/folders
    location ~ ^/users/(.+)/folders$ {
        try_files /users/$1/folders.json =404;
    }

    # GET /folders
    location = /folders {
        try_files /folders.json =404;
    }
}
